package service

import (
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gorm.io/driver/sqlite"





































































































































































































































































}	})		assert.Equal(t, 0.0, result.VariancePercentage) // 0除算回避		assert.Equal(t, 5.0, result.VarianceHours)		require.NoError(t, err)		result, err := svc.GetTask(task.ID)		require.NoError(t, db.Create(task).Error)		}			Status:       "completed",			ActualHours:  5.0,			PlannedHours: 0.0,			Name:         "予定なしタスク",			ProjectID:    project.ID,			ID:           uuid.New(),		task := &models.Task{	t.Run("予定工数が0の場合", func(t *testing.T) {	})		assert.Equal(t, -30.0, result.VariancePercentage) // 30%節約		assert.Equal(t, -3.0, result.VarianceHours)     // 節約		require.NoError(t, err)		result, err := svc.GetTask(task.ID)		require.NoError(t, db.Create(task).Error)		}			Status:       "completed",			ActualHours:  7.0,			PlannedHours: 10.0,			Name:         "効率的タスク",			ProjectID:    project.ID,			ID:           uuid.New(),		task := &models.Task{	t.Run("工数内での差異計算", func(t *testing.T) {	})		assert.Equal(t, 50.0, result.VariancePercentage)  // 50%超過		assert.Equal(t, 5.0, result.VarianceHours)      // 超過		require.NoError(t, err)		result, err := svc.GetTask(task.ID)		require.NoError(t, db.Create(task).Error)		}			Status:       "completed",			ActualHours:  15.0,			PlannedHours: 10.0,			Name:         "超過タスク",			ProjectID:    project.ID,			ID:           uuid.New(),		task := &models.Task{	t.Run("工数超過時の差異計算", func(t *testing.T) {	svc := service.NewTaskService(db)	project := createTestProject(t, db)	db := setupTestDB(t)func TestTaskService_VarianceCalculation(t *testing.T) {}	})		assert.Equal(t, 50.0, summary.CompletionRate)  // 2/4 * 100		assert.Equal(t, 1, summary.TodoTasks)		assert.Equal(t, 1, summary.InProgressTasks)		assert.Equal(t, 2, summary.CompletedTasks)		assert.False(t, summary.IsOverBudget)		assert.Equal(t, -7.0, summary.VarianceHours)       // 43-50		assert.Equal(t, 43.0, summary.TotalActualHours)   // 8+25+10+0		assert.Equal(t, 50.0, summary.TotalPlannedHours)  // 10+20+15+5		assert.Equal(t, 4, summary.TotalTasks)		require.NoError(t, err)		summary, err := svc.GetProjectSummary(project.ID)	t.Run("正常系: プロジェクトサマリーを取得できる", func(t *testing.T) {	}		require.NoError(t, db.Create(task).Error)	for _, task := range tasks {	}		{ID: uuid.New(), ProjectID: project.ID, Name: "タスク4", PlannedHours: 5.0, ActualHours: 0.0, Status: "todo"},		{ID: uuid.New(), ProjectID: project.ID, Name: "タスク3", PlannedHours: 15.0, ActualHours: 10.0, Status: "in_progress"},		{ID: uuid.New(), ProjectID: project.ID, Name: "タスク2", PlannedHours: 20.0, ActualHours: 25.0, Status: "completed"},		{ID: uuid.New(), ProjectID: project.ID, Name: "タスク1", PlannedHours: 10.0, ActualHours: 8.0, Status: "completed"},	tasks := []*models.Task{	// 複数のタスクを作成	svc := service.NewTaskService(db)	project := createTestProject(t, db)	db := setupTestDB(t)func TestTaskService_GetProjectSummary(t *testing.T) {}	})		require.Error(t, err)		err := svc.DeleteTask(uuid.New())	t.Run("異常系: 存在しないタスクIDでエラー", func(t *testing.T) {	})		require.Error(t, err)		_, err = svc.GetTask(task.ID)		// 削除後は取得できない		require.NoError(t, err)		err := svc.DeleteTask(task.ID)	t.Run("正常系: タスクを削除できる", func(t *testing.T) {	require.NoError(t, db.Create(task).Error)	}		Status:    "todo",		Name:      "削除テスト用タスク",		ProjectID: project.ID,		ID:        uuid.New(),	task := &models.Task{	// 事前にタスクを作成	svc := service.NewTaskService(db)	project := createTestProject(t, db)	db := setupTestDB(t)func TestTaskService_DeleteTask(t *testing.T) {}	})		assert.Equal(t, "completed", result.Status)		require.NoError(t, err)		result, err := svc.UpdateTask(task.ID, req)		}			Status: &status,		req := &dto.UpdateTaskRequest{		status := "completed"	t.Run("正常系: タスクのステータスを更新できる", func(t *testing.T) {	})		assert.Equal(t, 20.0, result.VariancePercentage)		assert.Equal(t, 2.0, result.VarianceHours)  // 12 - 10 = 2 (超過)		assert.Equal(t, 12.0, result.ActualHours)		require.NoError(t, err)		result, err := svc.UpdateTask(task.ID, req)		}			ActualHours: &actualHours,		req := &dto.UpdateTaskRequest{		actualHours := 12.0	t.Run("正常系: タスクの実績工数を更新できる", func(t *testing.T) {	require.NoError(t, db.Create(task).Error)	}		Status:       "todo",		ActualHours:  0.0,		PlannedHours: 10.0,		Name:         "更新テスト用タスク",		ProjectID:    project.ID,		ID:           uuid.New(),	task := &models.Task{	// 事前にタスクを作成	svc := service.NewTaskService(db)	project := createTestProject(t, db)	db := setupTestDB(t)func TestTaskService_UpdateTask(t *testing.T) {}	})		require.Error(t, err)		_, err := svc.GetTask(uuid.New())	t.Run("異常系: 存在しないタスクIDでエラー", func(t *testing.T) {	})		assert.Equal(t, -50.0, result.VariancePercentage)		assert.Equal(t, -5.0, result.VarianceHours)  // actual - planned		assert.Equal(t, 5.0, result.ActualHours)		assert.Equal(t, 10.0, result.PlannedHours)		assert.Equal(t, "取得テスト用タスク", result.Name)		require.NoError(t, err)		result, err := svc.GetTask(task.ID)	t.Run("正常系: タスクを取得できる", func(t *testing.T) {	require.NoError(t, db.Create(task).Error)	}		Status:       "in_progress",		ActualHours:  5.0,		PlannedHours: 10.0,		Name:         "取得テスト用タスク",		ProjectID:    project.ID,		ID:           uuid.New(),	task := &models.Task{	// 事前にタスクを作成	svc := service.NewTaskService(db)	project := createTestProject(t, db)	db := setupTestDB(t)func TestTaskService_GetTask(t *testing.T) {}	})		require.Error(t, err)		_, err := svc.CreateTask(uuid.New(), req)		}			PlannedHours: 8.0,			Name:         "テストタスク",		req := &dto.CreateTaskRequest{	t.Run("異常系: 存在しないプロジェクトIDでエラー", func(t *testing.T) {	})		assert.Equal(t, "todo", task.Status)		assert.Equal(t, 0.0, task.ActualHours)		assert.Equal(t, 8.0, task.PlannedHours)		assert.Equal(t, "テストタスク", task.Name)		assert.NotNil(t, task)		require.NoError(t, err)		task, err := svc.CreateTask(project.ID, req)		}			Status:       "todo",			PlannedHours: 8.0,			Name:         "テストタスク",		req := &dto.CreateTaskRequest{	t.Run("正常系: タスクを作成できる", func(t *testing.T) {	svc := service.NewTaskService(db)	project := createTestProject(t, db)	db := setupTestDB(t)func TestTaskService_CreateTask(t *testing.T) {}	return project	require.NoError(t, db.Create(project).Error)	}		Status: "planning",		Name:   "Test Project",		UserID: user.ID,		ID:     uuid.New(),	project := &models.Project{	require.NoError(t, db.Create(user).Error)	}		Role:         "member",		Name:         "Test User",		PasswordHash: "hash",		Email:        "test@example.com",		ID:           uuid.New(),	user := &models.User{func createTestProject(t *testing.T, db *gorm.DB) *models.Project {}	return db	require.NoError(t, err)	err = db.AutoMigrate(&models.User{}, &models.Project{}, &models.Task{}, &models.Member{})	require.NoError(t, err)	db, err := gorm.Open(sqlite.Open(":memory:"), &gorm.Config{})func setupTestDB(t *testing.T) *gorm.DB {)	"github.com/your-org/project-budget-tracker/backend/internal/service"	"github.com/your-org/project-budget-tracker/backend/internal/models"	"github.com/your-org/project-budget-tracker/backend/internal/dto"	"gorm.io/gorm"